import base64
from pathlib import Path
from unittest.mock import MagicMock, patch

from adf_scan.config import Config
from adf_scan.escl import ESCLError
from adf_scan.scanner import ScannerDaemon

# 100x100 white JPEG generated by Pillow
TINY_JPEG = base64.b64decode(
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRof"
    "Hh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwh"
    "MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAAR"
    "CABkAGQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA"
    "AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK"
    "FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWG"
    "h4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl"
    "5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA"
    "AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYk"
    "NOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE"
    "hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk"
    "5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoooo"
    "AKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK"
    "KACiiigD//2Q=="
)


def test_do_scan_creates_pdf(tmp_path: Path) -> None:
    config = Config(
        scanner_url="https://192.168.1.100/eSCL",
        scan_dir=tmp_path / "scans",
    )
    daemon = ScannerDaemon(config)
    daemon.client = MagicMock()
    daemon.client.create_scan_job.return_value = "/eSCL/ScanJobs/1"
    daemon.client.retrieve_pages.return_value = [TINY_JPEG]

    daemon._do_scan()

    pdfs = list((tmp_path / "scans").glob("scan_*.pdf"))
    assert len(pdfs) == 1
    assert pdfs[0].stat().st_size > 0
    daemon.client.delete_scan_job.assert_called_once_with("/eSCL/ScanJobs/1")


def test_do_scan_no_pages(tmp_path: Path) -> None:
    config = Config(
        scanner_url="https://192.168.1.100/eSCL",
        scan_dir=tmp_path / "scans",
    )
    daemon = ScannerDaemon(config)
    daemon.client = MagicMock()
    daemon.client.create_scan_job.return_value = "/eSCL/ScanJobs/2"
    daemon.client.retrieve_pages.return_value = []

    daemon._do_scan()

    pdfs = list((tmp_path / "scans").glob("scan_*.pdf"))
    assert len(pdfs) == 0


def test_run_stops_on_event(tmp_path: Path) -> None:
    config = Config(
        scanner_url="https://192.168.1.100/eSCL",
        scan_dir=tmp_path / "scans",
        poll_interval=0.1,
    )
    daemon = ScannerDaemon(config)
    daemon.client = MagicMock()
    daemon.client.adf_has_paper.side_effect = [False, False, ESCLError("fail")]

    # Stop after 3 poll cycles
    call_count = 0
    original_wait = daemon._stop.wait

    def counting_wait(timeout: float = 0) -> bool:
        nonlocal call_count
        call_count += 1
        if call_count >= 3:
            daemon.stop()
        return original_wait(timeout=0.01)

    daemon._stop.wait = counting_wait
    daemon.run()

    assert call_count >= 3
