apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adf-scan.fullname" . }}
  labels:
    {{- include "adf-scan.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "adf-scan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adf-scan.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "adf-scan.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "adf-scan.fullname" . }}
          volumeMounts:
            - name: scans
              mountPath: /scans
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: scans
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "adf-scan.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
